### PR TITLE
feat: add ethereum example

### PR DESCRIPTION
**Pull request by AgwaB**
- transaction signing
- message signing
- build erc20 transfer

### CODE REVIEW

**Review by baumstern — APPROVED** [review]

**Comment by zeroFruit** [comment]
**thought**: I'm a little worried because of the name of the package: "example". I saw many other projects using "example" as example code of their own project NOT reference code. In this case this is not example code of "Zulu" project. It is just about working reference code.

**Comment by junbeomlee** [comment]
Then how about putting it in the folder called `reference`?

**Comment by hihiboss** [comment]
I agree with @junbeomlee.

**Review by hihiboss — APPROVED** [review]
LGTM :)

**Pull request merged**
